# Generated by Django 6.0.3 on 2026-03-27 01:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentaccess',
            options={'verbose_name': 'Document Access', 'verbose_name_plural': 'Document Access'},
        ),
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together={('user', 'document')},
        ),
        migrations.AlterModelTable(
            name='documentaccess',
            table='DocumentAccess',
        ),
    ]
